/** biome-ignore-all lint/performance/noImgElement: This is a valid use case */
"use client";

import { Spinner } from "@/components/ui/spinner";
import {
  BASE_HEIGHT,
  BASE_WIDTH_PERCENTAGE,
} from "@/hooks/presentation/useRootImageActions";
import { cn } from "@/lib/utils";
import { usePresentationState } from "@/states/presentation-state";
import { ChartRenderer } from "../charts/ChartRenderer";
import { EmbedRenderer } from "../embeds/EmbedRenderer";
import ImagePlaceholder from "../image-placeholder";
import { type RootImageProps } from "../root-image";

export default function RootImageStatic({
  image,
  layoutType,
  slideId,
}: RootImageProps) {
  const isSideLayout = layoutType === "left" || layoutType === "right";
  const rootImageGeneration = usePresentationState(
    (s) => s.rootImageGeneration,
  );
  const computedGen = slideId ? rootImageGeneration[slideId] : undefined;
  const cropSettings = image.cropSettings || {
    objectFit: "cover" as const,
    objectPosition: { x: 50, y: 50 },
  };

  const imageStyles: React.CSSProperties = {
    objectFit: cropSettings.objectFit,
    objectPosition: `${cropSettings.objectPosition.x}% ${cropSettings.objectPosition.y}%`,
    transform: `scale(${cropSettings.zoom ?? 1})`,
    transformOrigin: `${cropSettings.objectPosition.x}% ${cropSettings.objectPosition.y}%`,
    height: "100%",
    width: "100%",
    display: "block",
  };

  const sizeStyle: React.CSSProperties = (() => {
    const hasExplicitHeight = Boolean(image.size?.h);
    const hasExplicitWidth = Boolean(image.size?.w);
    if (!hasExplicitHeight && !hasExplicitWidth) {
      if (layoutType === "vertical") {
        return { height: BASE_HEIGHT, width: "100%" } as const;
      }
      return { width: BASE_WIDTH_PERCENTAGE } as const;
    }
    if (layoutType === "vertical") {
      return { height: image.size?.h ?? BASE_HEIGHT, width: "100%" } as const;
    }
    return { width: image.size?.w ?? BASE_WIDTH_PERCENTAGE } as const;
  })();

  // Root image is now generated by PresentationGenerationManager

  return (
    <div
      className={cn(
        "relative shrink-0",
        isSideLayout && "min-h-0 self-stretch",
      )}
      style={sizeStyle}
    >
      <div
        className={cn(
          "overflow-hidden border bg-background/80 backdrop-blur-xs",
          isSideLayout ? "absolute inset-0" : "h-full",
        )}
        data-root-image={slideId}
        style={{
          borderRadius: "var(--presentation-border-radius, 0.5rem)",
          boxShadow:
            "var(--presentation-card-shadow, 0 1px 3px rgba(0,0,0,0.12))",
        }}
      >
        {computedGen?.status === "generating" ? (
          <div className="flex h-full flex-col items-center justify-center bg-muted/30 p-4">
            <Spinner className="mb-2 h-8 w-8" />
            <p className="text-sm text-muted-foreground">
              Generating image for &quot;{image.query}&quot;...
            </p>
          </div>
        ) : image.chartType && image.chartData ? (
          <div className="relative h-full" tabIndex={0}>
            <ChartRenderer
              chartType={image.chartType}
              chartData={image.chartData}
              chartOptions={image.chartOptions}
              className="h-full w-full"
            />
          </div>
        ) : image.embedType && image.url ? (
          <div className="relative h-full" tabIndex={0}>
            <EmbedRenderer
              embedType={image.embedType}
              url={image.url}
              className="h-full w-full"
              style={imageStyles}
            />
          </div>
        ) : (
          <div className="relative h-full" tabIndex={0}>
            {(computedGen?.status === "success" && computedGen.url) ||
            image.url ? (
              <img
                src={
                  (computedGen?.status === "success" && computedGen.url) ||
                  image.url
                }
                alt={image.query}
                style={imageStyles}
              />
            ) : (
              <ImagePlaceholder
                isStatic={true}
                className="h-full"
                slideId={slideId}
              />
            )}
          </div>
        )}
      </div>
    </div>
  );
}
