// Base template list
export const templates = [
  "chart-bar-plain-text",
  "chart-column-simple",
  "chart-line-plain-text",
  "chart-pie-compact-card",
  "chart-pie-donut-compact-card",
  "chart-pie-donut-pill-badge",
  "chart-pie-donut-plain-text",
  "chart-pie-pill-badge",
  "chart-pie-plain-text",
  "chart-wordcloud",
  "chart-wordcloud-rotate",
  "compare-binary-horizontal-badge-card-arrow",
  "compare-binary-horizontal-badge-card-fold",
  "compare-binary-horizontal-badge-card-vs",
  "compare-binary-horizontal-compact-card-arrow",
  "compare-binary-horizontal-compact-card-fold",
  "compare-binary-horizontal-compact-card-vs",
  "compare-binary-horizontal-simple-arrow",
  "compare-binary-horizontal-simple-fold",
  "compare-binary-horizontal-simple-vs",
  "compare-binary-horizontal-underline-text-arrow",
  "compare-binary-horizontal-underline-text-fold",
  "compare-binary-horizontal-underline-text-vs",
  "compare-hierarchy-left-right-circle-node-pill-badge",
  "compare-hierarchy-left-right-circle-node-plain-text",
  "compare-hierarchy-row-letter-card-compact-card",
  "compare-hierarchy-row-letter-card-rounded-rect-node",
  "compare-swot",
  "hierarchy-mindmap-branch-gradient-capsule-item",
  "hierarchy-mindmap-branch-gradient-circle-progress",
  "hierarchy-mindmap-branch-gradient-compact-card",
  "hierarchy-mindmap-branch-gradient-lined-palette",
  "hierarchy-mindmap-branch-gradient-rounded-rect",
  "hierarchy-mindmap-level-gradient-capsule-item",
  "hierarchy-mindmap-level-gradient-circle-progress",
  "hierarchy-mindmap-level-gradient-compact-card",
  "hierarchy-mindmap-level-gradient-lined-palette",
  "hierarchy-mindmap-level-gradient-rounded-rect",
  "hierarchy-structure",
  "hierarchy-structure-mirror",
  "hierarchy-tree-bt-curved-line-badge-card",
  "hierarchy-tree-bt-curved-line-capsule-item",
  "hierarchy-tree-bt-curved-line-compact-card",
  "hierarchy-tree-bt-curved-line-ribbon-card",
  "hierarchy-tree-bt-curved-line-rounded-rect-node",
  "hierarchy-tree-bt-dashed-arrow-badge-card",
  "hierarchy-tree-bt-dashed-arrow-capsule-item",
  "hierarchy-tree-bt-dashed-arrow-compact-card",
  "hierarchy-tree-bt-dashed-arrow-ribbon-card",
  "hierarchy-tree-bt-dashed-arrow-rounded-rect-node",
  "hierarchy-tree-bt-dashed-line-badge-card",
  "hierarchy-tree-bt-dashed-line-capsule-item",
  "hierarchy-tree-bt-dashed-line-compact-card",
  "hierarchy-tree-bt-dashed-line-ribbon-card",
  "hierarchy-tree-bt-dashed-line-rounded-rect-node",
  "hierarchy-tree-bt-distributed-origin-badge-card",
  "hierarchy-tree-bt-distributed-origin-capsule-item",
  "hierarchy-tree-bt-distributed-origin-compact-card",
  "hierarchy-tree-bt-distributed-origin-ribbon-card",
  "hierarchy-tree-bt-distributed-origin-rounded-rect-node",
  "hierarchy-tree-bt-tech-style-badge-card",
  "hierarchy-tree-bt-tech-style-capsule-item",
  "hierarchy-tree-bt-tech-style-compact-card",
  "hierarchy-tree-bt-tech-style-ribbon-card",
  "hierarchy-tree-bt-tech-style-rounded-rect-node",
  "hierarchy-tree-curved-line-badge-card",
  "hierarchy-tree-curved-line-capsule-item",
  "hierarchy-tree-curved-line-compact-card",
  "hierarchy-tree-curved-line-ribbon-card",
  "hierarchy-tree-curved-line-rounded-rect-node",
  "hierarchy-tree-dashed-arrow-badge-card",
  "hierarchy-tree-dashed-arrow-capsule-item",
  "hierarchy-tree-dashed-arrow-compact-card",
  "hierarchy-tree-dashed-arrow-ribbon-card",
  "hierarchy-tree-dashed-arrow-rounded-rect-node",
  "hierarchy-tree-dashed-line-badge-card",
  "hierarchy-tree-dashed-line-capsule-item",
  "hierarchy-tree-dashed-line-compact-card",
  "hierarchy-tree-dashed-line-ribbon-card",
  "hierarchy-tree-dashed-line-rounded-rect-node",
  "hierarchy-tree-distributed-origin-badge-card",
  "hierarchy-tree-distributed-origin-capsule-item",
  "hierarchy-tree-distributed-origin-compact-card",
  "hierarchy-tree-distributed-origin-ribbon-card",
  "hierarchy-tree-distributed-origin-rounded-rect-node",
  "hierarchy-tree-lr-curved-line-badge-card",
  "hierarchy-tree-lr-curved-line-capsule-item",
  "hierarchy-tree-lr-curved-line-compact-card",
  "hierarchy-tree-lr-curved-line-ribbon-card",
  "hierarchy-tree-lr-curved-line-rounded-rect-node",
  "hierarchy-tree-lr-dashed-arrow-badge-card",
  "hierarchy-tree-lr-dashed-arrow-capsule-item",
  "hierarchy-tree-lr-dashed-arrow-compact-card",
  "hierarchy-tree-lr-dashed-arrow-ribbon-card",
  "hierarchy-tree-lr-dashed-arrow-rounded-rect-node",
  "hierarchy-tree-lr-dashed-line-badge-card",
  "hierarchy-tree-lr-dashed-line-capsule-item",
  "hierarchy-tree-lr-dashed-line-compact-card",
  "hierarchy-tree-lr-dashed-line-ribbon-card",
  "hierarchy-tree-lr-dashed-line-rounded-rect-node",
  "hierarchy-tree-lr-distributed-origin-badge-card",
  "hierarchy-tree-lr-distributed-origin-capsule-item",
  "hierarchy-tree-lr-distributed-origin-compact-card",
  "hierarchy-tree-lr-distributed-origin-ribbon-card",
  "hierarchy-tree-lr-distributed-origin-rounded-rect-node",
  "hierarchy-tree-lr-tech-style-badge-card",
  "hierarchy-tree-lr-tech-style-capsule-item",
  "hierarchy-tree-lr-tech-style-compact-card",
  "hierarchy-tree-lr-tech-style-ribbon-card",
  "hierarchy-tree-lr-tech-style-rounded-rect-node",
  "hierarchy-tree-rl-curved-line-badge-card",
  "hierarchy-tree-rl-curved-line-capsule-item",
  "hierarchy-tree-rl-curved-line-compact-card",
  "hierarchy-tree-rl-curved-line-ribbon-card",
  "hierarchy-tree-rl-curved-line-rounded-rect-node",
  "hierarchy-tree-rl-dashed-arrow-badge-card",
  "hierarchy-tree-rl-dashed-arrow-capsule-item",
  "hierarchy-tree-rl-dashed-arrow-compact-card",
  "hierarchy-tree-rl-dashed-arrow-ribbon-card",
  "hierarchy-tree-rl-dashed-arrow-rounded-rect-node",
  "hierarchy-tree-rl-dashed-line-badge-card",
  "hierarchy-tree-rl-dashed-line-capsule-item",
  "hierarchy-tree-rl-dashed-line-compact-card",
  "hierarchy-tree-rl-dashed-line-ribbon-card",
  "hierarchy-tree-rl-dashed-line-rounded-rect-node",
  "hierarchy-tree-rl-distributed-origin-badge-card",
  "hierarchy-tree-rl-distributed-origin-capsule-item",
  "hierarchy-tree-rl-distributed-origin-compact-card",
  "hierarchy-tree-rl-distributed-origin-ribbon-card",
  "hierarchy-tree-rl-distributed-origin-rounded-rect-node",
  "hierarchy-tree-rl-tech-style-badge-card",
  "hierarchy-tree-rl-tech-style-capsule-item",
  "hierarchy-tree-rl-tech-style-compact-card",
  "hierarchy-tree-rl-tech-style-ribbon-card",
  "hierarchy-tree-rl-tech-style-rounded-rect-node",
  "hierarchy-tree-tech-style-badge-card",
  "hierarchy-tree-tech-style-capsule-item",
  "hierarchy-tree-tech-style-compact-card",
  "hierarchy-tree-tech-style-ribbon-card",
  "hierarchy-tree-tech-style-rounded-rect-node",
  "list-column-done-list",
  "list-column-simple-vertical-arrow",
  "list-column-vertical-icon-arrow",
  "list-grid-badge-card",
  "list-grid-candy-card-lite",
  "list-grid-circular-progress",
  "list-grid-compact-card",
  "list-grid-done-list",
  "list-grid-horizontal-icon-arrow",
  "list-grid-progress-card",
  "list-grid-ribbon-card",
  "list-grid-simple",
  "list-pyramid-badge-card",
  "list-pyramid-compact-card",
  "list-pyramid-rounded-rect-node",
  "list-row-circular-progress",
  "list-row-horizontal-icon-arrow",
  "list-row-horizontal-icon-line",
  "list-row-simple-horizontal-arrow",
  "list-row-simple-illus",
  "list-sector-half-plain-text",
  "list-sector-plain-text",
  "list-sector-simple",
  "list-zigzag-down-compact-card",
  "list-zigzag-down-simple",
  "list-zigzag-up-compact-card",
  "list-zigzag-up-simple",
  "quadrant-quarter-circular",
  "quadrant-quarter-simple-card",
  "quadrant-simple-illus",
  "relation-circle-circular-progress",
  "relation-circle-icon-badge",
  "relation-dagre-flow-lr-animated-badge-card",
  "relation-dagre-flow-lr-animated-capsule",
  "relation-dagre-flow-lr-animated-compact-card",
  "relation-dagre-flow-lr-animated-simple-circle-node",
  "relation-dagre-flow-lr-badge-card",
  "relation-dagre-flow-lr-compact-card",
  "relation-dagre-flow-lr-simple-circle-node",
  "relation-dagre-flow-tb-animated-badge-card",
  "relation-dagre-flow-tb-animated-capsule",
  "relation-dagre-flow-tb-animated-compact-card",
  "relation-dagre-flow-tb-animated-simple-circle-node",
  "relation-dagre-flow-tb-badge-card",
  "relation-dagre-flow-tb-compact-card",
  "relation-dagre-flow-tb-simple-circle-node",
  "sequence-ascending-stairs-3d-simple",
  "sequence-ascending-stairs-3d-underline-text",
  "sequence-ascending-steps",
  "sequence-circle-arrows-indexed-card",
  "sequence-circular-simple",
  "sequence-circular-underline-text",
  "sequence-color-snake-steps-horizontal-icon-line",
  "sequence-color-snake-steps-simple-illus",
  "sequence-cylinders-3d-simple",
  "sequence-filter-mesh-simple",
  "sequence-filter-mesh-underline-text",
  "sequence-funnel-simple",
  "sequence-horizontal-zigzag-horizontal-icon-line",
  "sequence-horizontal-zigzag-plain-text",
  "sequence-horizontal-zigzag-simple",
  "sequence-horizontal-zigzag-simple-horizontal-arrow",
  "sequence-horizontal-zigzag-simple-illus",
  "sequence-horizontal-zigzag-underline-text",
  "sequence-mountain-underline-text",
  "sequence-pyramid-simple",
  "sequence-roadmap-vertical-badge-card",
  "sequence-roadmap-vertical-pill-badge",
  "sequence-roadmap-vertical-plain-text",
  "sequence-roadmap-vertical-quarter-circular",
  "sequence-roadmap-vertical-quarter-simple-card",
  "sequence-roadmap-vertical-simple",
  "sequence-roadmap-vertical-underline-text",
  "sequence-snake-steps-compact-card",
  "sequence-snake-steps-pill-badge",
  "sequence-snake-steps-simple",
  "sequence-snake-steps-simple-illus",
  "sequence-snake-steps-underline-text",
  "sequence-stairs-front-compact-card",
  "sequence-stairs-front-pill-badge",
  "sequence-stairs-front-simple",
  "sequence-steps-badge-card",
  "sequence-steps-simple",
  "sequence-steps-simple-illus",
  "sequence-timeline-done-list",
  "sequence-timeline-plain-text",
  "sequence-timeline-rounded-rect-node",
  "sequence-timeline-simple",
  "sequence-timeline-simple-illus",
  "sequence-zigzag-pucks-3d-indexed-card",
  "sequence-zigzag-pucks-3d-simple",
  "sequence-zigzag-pucks-3d-underline-text",
  "sequence-zigzag-steps-underline-text",
];

// ============================================================================
// SIMPLE CATEGORY STRUCTURE - 7 main categories only
// ============================================================================

export interface InfographicCategory {
  key: string;
  name: string;
  templates: string[]; // Template IDs
  dataField: InfographicDataField;
}

export type InfographicDataField =
  | "items"
  | "root"
  | "nodes"
  | "values"
  | "compares"
  | "lists"
  | "sequences";

// Simple 7 categories matching the reference image
export const INFOGRAPHIC_CATEGORIES: InfographicCategory[] = [
  {
    key: "chart",
    name: "Chart",
    templates: templates.filter((t) => t.startsWith("chart-")),
    dataField: "items",
  },
  {
    key: "compare",
    name: "Comparison",
    templates: templates.filter((t) => t.startsWith("compare-")),
    dataField: "compares",
  },
  {
    key: "hierarchy",
    name: "Hierarchy",
    templates: templates.filter((t) => t.startsWith("hierarchy-")),
    dataField: "root",
  },
  {
    key: "list",
    name: "List",
    templates: templates.filter((t) => t.startsWith("list-")),
    dataField: "items",
  },
  {
    key: "quadrant",
    name: "Quadrant",
    templates: templates.filter((t) => t.startsWith("quadrant-")),
    dataField: "items",
  },
  {
    key: "relation",
    name: "Relation",
    templates: templates.filter((t) => t.startsWith("relation-")),
    dataField: "items",
  },
  {
    key: "sequence",
    name: "Sequence",
    templates: templates.filter((t) => t.startsWith("sequence-")),
    dataField: "items",
  },
];

// Get category for a template ID
export function getTemplateCategory(
  templateId: string,
): InfographicCategory | undefined {
  return INFOGRAPHIC_CATEGORIES.find((cat) =>
    cat.templates.includes(templateId),
  );
}
